### ISSUE TITLE
Fingerprinting mp4 files FormatConversionProvider

### ISSUE THREAD

**Issue by salamanders** [wsieroci/audio-recognizer#1]
Great demo code, thank you!
I was wondering if you have ever seen a way to have a FormatConversionProvider for a mp4 audio file?  I was hoping to try your code on my own library, but with the defaults being mp4 instead of mp3, no such luck.

**Comment by RAJAmaaz** [comment]
Hi salamanders
hope you are fine.Is this code running fine on your side?
Need help brother. I have to recognize same audios in my project,

reply please

Thanks
![untitled](https://cloud.githubusercontent.com/assets/11872834/23091588/6ed201cc-f5db-11e6-846a-f8beddfb6eee.png)

**Comment by salamanders** [comment]
Unfortunately I never did get this working.
